version: "3"
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - database

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./.env.db
    environment:
      - TZ=Asia/Seoul
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: